# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 22:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosario_construction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_info',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clients_info',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='clients_info',
            name='phone_number',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')]),
        ),
    ]
